log‐level: "info"
threads: 3
queue‐depth: 4
fail‐threshold: 5
signal‐on‐fail: false
image‐buffer‐size: 100
output‐path: "/home/user/agvision"
camera:
  type: "icube"
  exposure: 1.0
  gain: 64.0
  trigger‐delay: 0.07
  strobe‐length: 1.0
  strobe‐delay: 0.07
  flip: true
scanners:
    - name         : "Barcode"
      type         : "barcode"
      enabled      : true
      roi          : [0, 200, 640, 280]
      vertical     : false
      scan‐density : 2
      symbology    : "databar"
      content      : "0100151972708880"
    - name         : "PLU"
      type         : "ocr"
      enabled      : true
      roi          : [0, 272, 640, 40]
      vertical     : false
      numeric      : true
      content      : "2015"